name: "Continuous Integration with CodeQL"

on:
  push:
  pull_request:

# largely cribbed from https://github.com/github/codeql-action
jobs:
  CodeQL-Build:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head of the pull request.
          # Only include this option if you are running this workflow on pull requests.
          fetch-depth: 2

      # If this run was triggered by a pull request event then checkout
      # the head of the pull request instead of the merge commit.
      # Only include this step if you are running this workflow on pull requests.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      # Initializes the CodeQL tools for scanning.
      - name: Download CodeQL
        run: |
          echo "$PWD"
          mkdir "$HOME/codeql-home"
          cd "$HOME/codeql-home"
          echo "$PWD"
          ls -lha .
          sleep 1
          echo "running curl -SsO in $PWD"
          curl -SsOL https://github.com/github/codeql-cli-binaries/releases/download/v2.2.4/codeql-linux64.zip
          sleep 1
          echo "$PWD"
          ls -lha .
          sleep 1
          echo "running unzip in $PWD"
          unzip -q codeql-linux64.zip
          sleep 1
          echo "$PWD"
          ls -lha .

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build & run specs
        env:
          CODEQL_PATH: "$HOME/codeql-home/codeql/codeql"
        run: |
          echo "$PWD"
          ls -lha .
          sleep 1
          ls -lha "$GITHUB_WORKSPACE"
          sleep 1
          ls -lha "$HOME"
          sleep 1
          ls -lha "$HOME/codeql-home"
          sleep 1
          echo "running ln -s '$GITHUB_WORKSPACE' '$HOME/codeql-home/codeql-ruby-dir' in directory $PWD"
          sleep 1
          ln -s "$GITHUB_WORKSPACE" "$HOME/codeql-home/codeql-ruby-dir"
          sleep 1
          gem install bundler
          bundle install
          rake spec:ci

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v2

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 https://git.io/JvXDl

      # ✏️ If the Autobuild fails above, remove it and uncomment the following
      #    three lines and modify them (or add more) to build your code if your
      #    project uses a compiled language

      #- run: |
      #   make bootstrap
      #   make release

      # - name: Perform CodeQL Analysis
      #   uses: github/codeql-action/analyze@v1
